### ISSUE TITLE
Interfaces generated for classes with `override` or `new` methods contain duplicates

### ISSUE THREAD

**Issue by simonmckenzie** [codecentric/net_automatic_interface#50]
The current code will insert multiple definitions of a method when that method has been overridden or shadowed via `new`.

For example, given these two classes:

```csharp
public class BaseClass
{
    public virtual bool AMethod();
}

[GenerateAutomaticInterface]
public class DemoClass : BaseClass
{
    public override bool AMethod() => return true;
}
```

The generated interface will look like this:

```csharp
[GeneratedCode("AutomaticInterface", "")]
public partial interface IDemoClass
{
    /// <inheritdoc />
    bool AMethod();
        
    /// <inheritdoc />
    bool AMethod();
}
```

**Comment by simonmckenzie** [comment]
Resolved by the merge of #51

**Comment by FinnAngelo** [comment]
Hi all
FYI: it doesn't look like the fix is sticking - the error is still showing with this;

```csproj
<PackageReference Include="AutomaticInterface" Version="2.5.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

```csharp
file class GenerateAutomaticInterface : Attribute;

[GenerateAutomaticInterface]
file class MyButton : System.Windows.Forms.Button
{
    public new event System.EventHandler? ImeModeChanged;
}
```

I really like the package though - thanks for your work so far!

**Comment by simonmckenzie** [comment]
HI @FinnAngelo,

My fix was only for methods. It looks like we'll need another one for events 🤦 

Would you be interested in doing this? It'll be much the same as in this PR: https://github.com/codecentric/net_automatic_interface/pull/33

If not, I can have a look later in the week.

**Comment by FinnAngelo** [comment]
Hi @simonmckenzie  - I wont be able to start till this weekend (Sat 10 Aug) but yeah, sure!
